-- Catálogo inicial de códigos contables del comercio chileno.
INSERT INTO codigos (id, nombre, categoria, descripcion, activo) VALUES
  ('COVE', 'Costo de Ventas',                'Costo de venta',         'Compras y costos asociados a la venta de productos', true),
  ('IVEN', 'Ingreso por Ventas',             'Ventas',                 'Ingresos provenientes de ventas de productos o servicios', true),
  ('MER',  'Mercaderías',                    'Costo de venta',         'Compra de mercaderías para reventa', true),
  ('REMU', 'Remuneraciones',                 'Remuneraciones',         'Sueldos, salarios y pagos al personal', true),
  ('INCE', 'Incentivos y Bonos',             'Remuneraciones',         'Bonos de productividad, incentivos', true),
  ('CRGA', 'Cargas Sociales',                'Remuneraciones',         'Cotizaciones previsionales, AFP, Fonasa, Isapre', true),
  ('ARRI', 'Arriendo',                       'Arriendo',               'Arriendo de oficinas, locales, bodegas', true),
  ('INMO', 'Gastos Inmobiliarios',           'Arriendo',               'Gastos comunes, contribuciones', true),
  ('HONO', 'Honorarios',                     'Servicios profesionales','Honorarios por servicios profesionales', true),
  ('ASES', 'Asesorías',                      'Servicios profesionales','Asesorías legales, tributarias, financieras', true),
  ('CAPA', 'Capacitación',                   'Capacitación',           'Cursos, seminarios, becas de estudio', true),
  ('IMPU', 'Impuestos',                      'Impuestos',              'Pago de impuestos', true),
  ('IVAA', 'IVA',                            'Impuestos',              'IVA débito y crédito fiscal', true),
  ('RETE', 'Retenciones',                    'Impuestos',              'Retenciones de impuestos', true),
  ('PATE', 'Patentes Municipales',           'Impuestos',              'Patentes y permisos municipales', true),
  ('COMI', 'Comisiones Bancarias',           'Gastos bancarios',       'Comisiones y cargos bancarios', true),
  ('INTE', 'Intereses',                      'Gastos financieros',     'Intereses bancarios y financieros', true),
  ('PRES', 'Préstamos',                      'Gastos financieros',     'Cuotas y amortización de préstamos', true),
  ('DESC', 'Descuentos Obtenidos',           'Ingresos financieros',   'Descuentos por pronto pago', true),
  ('ENER', 'Energía Eléctrica',              'Servicios básicos',      'Cuentas de electricidad', true),
  ('AGUA', 'Agua Potable',                   'Servicios básicos',      'Cuentas de agua', true),
  ('TELE', 'Telefonía e Internet',           'Servicios básicos',      'Teléfono, internet, cable', true),
  ('SEGU', 'Seguros',                        'Seguros',                'Seguros generales, vehículos, vida', true),
  ('MANT', 'Mantención',                     'Mantención',             'Mantención y reparaciones', true),
  ('VIAJ', 'Viajes y Viáticos',              'Viajes',                 'Pasajes, hospedaje, viáticos', true),
  ('PUBL', 'Publicidad',                     'Publicidad',             'Publicidad y marketing', true),
  ('TRAN', 'Transporte',                     'Transporte',             'Fletes, encomiendas, transporte', true),
  ('COMB', 'Combustible',                    'Combustible',            'Combustibles y lubricantes', true),
  ('MATR', 'Materiales',                     'Materiales',             'Materiales de oficina y operación', true),
  ('EQUI', 'Equipos',                        'Equipos',                'Equipos computacionales y tecnológicos', true),
  ('MUEB', 'Mobiliario',                     'Mobiliario',             'Mobiliario y decoración', true),
  ('VEHI', 'Vehículos',                      'Vehículos',              'Vehículos y transporte propio', true),
  ('LIMP', 'Limpieza',                       'Servicios básicos',      'Productos y servicios de limpieza', true),
  ('VIGI', 'Vigilancia',                     'Servicios básicos',      'Servicios de seguridad y vigilancia', true),
  ('COST', 'Costas Judiciales',              'Gastos legales',         'Costas y gastos judiciales', true),
  ('MULT', 'Multas',                         'Gastos legales',         'Multas y sanciones', true),
  ('DEVO', 'Devoluciones',                   'Devoluciones',           'Devoluciones de dinero o productos', true),
  ('PROP', 'Propinas',                       'Gastos generales',       'Propinas y gratificaciones', true),
  ('ALIM', 'Alimentación',                   'Gastos generales',       'Gastos de alimentación y casino', true),
  ('SUMI', 'Suministros',                    'Gastos generales',       'Suministros menores', true),
  ('DONC', 'Donaciones',                     'Gastos generales',       'Donaciones y aportes', true),
  ('GAST', 'Gastos Generales',               'Gastos generales',       'Gastos generales no clasificados', true),
  ('INVA', 'Inversión en Activos',           'Inversiones',            'Compra de activos fijos e inversiones', true),
  ('INGR', 'Otros Ingresos',                 'Otros ingresos',         'Otros ingresos no clasificados', true),
  ('EGRE', 'Otros Egresos',                  'Otros egresos',          'Otros egresos no clasificados', true),
  ('DEPR', 'Depreciación',                   'Depreciación',           'Depreciación de activos fijos', true),
  ('AMRT', 'Amortización',                   'Amortización',           'Amortización de intangibles', true)
ON CONFLICT (id) DO NOTHING;